# editors and debuggers need to be responsive
_monorail_cmd_interactive 📝 nvim 
_monorail_cmd_interactive 📝 vim 
_monorail_cmd_interactive 📝 joe 
_monorail_cmd_interactive 📝 mg 
_monorail_cmd_interactive 📝 nano 
_monorail_cmd_interactive 📝 pico 
_monorail_cmd_interactive 📝 em 
_monorail_cmd_interactive 📓 man
_monorail_cmd_interactive 📈 top
_monorail_cmd_interactive 📈 ntop
_monorail_cmd_interactive 📈 nvtop
_monorail_cmd_interactive 📈 htop
_monorail_cmd_interactive 📈 nload
_monorail_cmd_interactive 🤖 adb
_monorail_cmd_interactive 🤖 gdb

# do not add icon info for the following commands
_monorail_cmd_ignored ls
_monorail_cmd_ignored ll
_monorail_cmd_ignored cd

# shells are listed as batch commands
# since these are often used to call a heavy batch script
# for interactive use, call the shell as 'exec bash'
_monorail_cmd_batch 🐚 bash
_monorail_cmd_batch 🐚 zsh
_monorail_cmd_batch 🐚 ksh
_monorail_cmd_batch 🐚 sh
_monorail_cmd_batch 🐍 python
_monorail_cmd_batch 🐍 python3
_monorail_cmd_batch 🐿️ go
_monorail_cmd_batch 🦀 cargo
_monorail_cmd_batch 🐋 docker
_monorail_cmd_batch 🦭 podman

# Compilers and build systems can take a long time and use lots of computer
# resources.
# Use low priority so rest of the system becomes available in the mean time
_monorail_cmd_batch 🛠️ clang
_monorail_cmd_batch 🛠️ gcc
_monorail_cmd_batch 🛠️ gcc
_monorail_cmd_batch 🛠️ g++
_monorail_cmd_batch 🛠️ snapcraft
_monorail_cmd_batch 🛠️ ninja
_monorail_cmd_batch 🛠️ make
_monorail_cmd_batch 🛠️ just
_monorail_cmd_batch 🛠️ jhbuild
_monorail_cmd_batch 🛠️ bitbake
_monorail_cmd_batch 🛠️ meson
_monorail_cmd_batch 🛠️ cmake

_monorail_cmd_batch 🗜️ gzip
_monorail_cmd_batch 🗜️ unrar
_monorail_cmd_batch 🗜️ 7z
_monorail_cmd_batch 🗜️ unar
_monorail_cmd_batch 🗜️ bzip2
_monorail_cmd_batch 🗜️ xz
_monorail_cmd_batch 🗜️ zstd
_monorail_cmd_batch 🧮 bc
_monorail_cmd_batch 🪚 awk
_monorail_cmd_batch 🐈 cat
_monorail_cmd_batch Δ delta
_monorail_cmd_batch Δ diff
_monorail_cmd_batch 💽 cp
_monorail_cmd_batch 💽 dd
_monorail_cmd_batch 📼 tar
_monorail_cmd_batch 🪣 repo
_monorail_cmd_batch 🪣 git
_monorail_cmd_batch 🪣 svn
_monorail_cmd_batch 🪣 hg
_monorail_cmd_batch 🪣 cvs
_monorail_cmd_batch 🔎 fd
_monorail_cmd_batch 🔎 fdfind
_monorail_cmd_batch 🔎 find
_monorail_cmd_batch 🔎 rga
_monorail_cmd_batch 🔎 rg
_monorail_cmd_batch 👣 strace
_monorail_cmd_batch ♻️  rm 
_monorail_cmd_batch ♻️  jdupes
_monorail_cmd_batch ♻️  fclones

