# License:  GPL-2.0-or-later
# https://github.com/gnachman/iTerm2/blob/master/plists/ColorPresets.plistComes from iTerm2 v3.4.19
_COLORS \
000000 \
c91b00 \
00c200 \
c7c400 \
2225c4 \
ca30c7 \
00c5c7 \
ffffff \
686868 \
ff6e67 \
5ffa68 \
fffc67 \
6871ff \
ff77ff \
60fdff \
ffffff \
ffffff \
000000 \
ffffff \
c1deff \
000000 \
e5e5e5
