# License: MIT
# https://github.com/mbadolato/iTerm2-Color-Schemes/pull/241Color values match the Material Darker from material.nvim
_monorail_colors \
000000 \
ff5370 \
c3e88d \
ffcb6b \
82aaff \
c792ea \
89ddff \
ffffff \
545454 \
ff5370 \
c3e88d \
ffcb6b \
82aaff \
c792ea \
89ddff \
ffffff \
eeffff \
212121 \
ffffff \
eeffff \
545454 \
ffffff
