_monorail_folder home 🏠
_monorail_folder ssh 🌐
_monorail_folder docker 🐋
_monorail_folder podman 🦭
_monorail_folder git 🚧
_monorail_folder repo 🏗️
_monorail_folder trash 🗑️
_monorail_folder documents 📑;
_monorail_folder media 💾
_monorail_folder music 🎵
_monorail_folder videos 🎬
_monorail_folder downloads 📦
_monorail_folder settings ⚙️
_monorail_folder fallback 📂
