_monorail_folder_home 🏠
_monorail_folder_ssh 🌐
_monorail_folder_docker 🐋
_monorail_folder_podman 🦭
_monorail_folder_git 🚧
_monorail_folder_repo 🏗️
_monorail_folder_trash 🗑️
_monorail_folder_documents
_monorail_folder_media 💾
_monorail_folder_music 🎵
_monorail_folder_videos 🎬
_monorail_folder_downloads 📦
_monorail_folder_settings ⚙️
_monorail_folder_fallback 📂
